#ifndef SHADER_CPP_COMMON_H
#define SHADER_CPP_COMMON_H

#define MAX_CASCADE_NUM		4
#define MAX_INSTANCE_COUNT	256

#define USE_AMPLIFICATION_SHADER
#define USE_MESHLET_CULLING

#define AS_GROUP_SIZE 32

#define MAX_INDEXED_VERTEX_NUM_PER_MESHLET_VL 64
#define MAX_INDEXED_TRI_NUM_PER_MESHLET_VL 64

#define MAX_INDEXED_VERTEX_NUM_PER_MESHLET_LM 256
#define MAX_INDEXED_TRI_NUM_PER_MESHLET_LM 256

#define USE_INSTANCING

#ifdef STEREO_RENDER
	#define VIEW_PROJ_ARRAY_COUNT 2
#else
	#define VIEW_PROJ_ARRAY_COUNT 1
#endif

#endif